CHANGES : * pms-linux -> new patches, i did not include resources/ dir before,             but now i do ;)           * redmine           * minor changes in paissad.SlackBuild, nothing really important !
git-svn-id: https://svn.paissad.net/slackbuilds/stable@21 a8e915ae-7a13-4794-ad7b-daf03aeeedbb

diff --git a/paissad.SlackBuild b/paissad.SlackBuild
--- a/paissad.SlackBuild
+++ b/paissad.SlackBuild
@@ -26,7 +26,7 @@
 time_start_script=$(date +%s)
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
-PACKAGER=${PACKAGER:-$USER@$(cat /etc/HOSTNAME)}
+PACKAGER=${PACKAGER:-$USER@$HOSTNAME}
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
 PRGNAM=${PRGNAM:-}
@@ -43,14 +43,16 @@ SOURCE=${SRCNAM}-${VERSION}.$EXT
 URL=${URL:-http://downloads.sourceforge.net/project/$SOURCE}
 TAG=${TAG:-_paissad}
 PKGTYPE=${PKGTYPE:-tgz}
-PREFIX=${PREFIX:-"/usr"}
+PREFIX="${PREFIX:-/usr}"
 NUMJOBS=${NUMJOBS:-}
 DOCS=${DOCS:-"CREDITS WHISHLIST ABOUT-NLS AUTHORS COPYING LICENSE* \
 CHANGES CHANGELOG* ChangeLog* HACKING INSTALL* MAINTAINERS NEWS \
 ReadMe* README* THANKS TODO Todo RELEASE* UPGRADING* FAQ Faq HELP* BUGS*"}
 
 set -e
+trap shellout EXIT
 
+# Colors#{{{
 txtred=$'\e[0;31m' # Red
 txtgrn=$'\e[0;32m' # Green
 txtylw=$'\e[0;33m' # Yellow
@@ -58,46 +60,51 @@ txtblu=$'\e[0;34m' # Blue
 txtpur=$'\e[0;35m' # Purple
 txtcyn=$'\e[0;36m' # Cyan
 txtrst=$'\e[0m'    # Text Reset
+##}}}
 
+# Fancy functions#{{{
 frame()
 {
     WIDTH=78
-    STARS="++----------------------------------------------------------------------------+"
-    SPACES="                                                                               "
-    printf "%s\n" "${STARS:1:$WIDTH}"
+    STARS="+";for ((i=1; i<=$(($WIDTH-2)); i++));do STARS+="-";done; STARS+="+"
+    SPACES="";for ((i=1; i<$WIDTH; i++)); do SPACES+=" "; done
+    printf "%s\n" "${STARS:0:$WIDTH}"
     while read line ; do
         HALF="${SPACES:1:$((($WIDTH-${#line})/2))}"
         LINE="$HALF$line$SPACES"
         printf "+%s+\n" "${LINE:1:$(($WIDTH-2))}"
     done
-    printf "%s\n" "${STARS:1:$WIDTH}"
+    printf "%s\n" "${STARS:0:$WIDTH}"
 }
 introduce(){
-    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst \c "; sleep 2;
+    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst\c"; sleep 2;
 }
 conclude(){
     echo -e "${txtgrn}\n# $1 \n${txtrst}"; sleep 2;
 }
 shellout(){
-    echo -e "${txtred}Error:${txtrst} $1 ${txtcyn}(exit status -> $?)${txtrst}"; exit 1;
+  ret=$?
+    if (($ret)); then
+        echo -e "${txtred}Error:${txtrst} $process failed ! ${txtcyn}"
+    echo -e "(exit status of last command -> $ret)${txtrst}"
+      exit 1;
+    fi
 }
-warnout(){
-    echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
-}
+##}}}
 
-# Download of the source !
+# Download of the source !#{{{
 if [ ! -r $SOURCE ]; then
     introduce "Start downloading $SOURCE" 
-    wget "$URL" || shellout "Downloading $SOURCE"
+    wget "$URL"
     conclude "Download of $SOURCE finished successfully !"
 fi
+##}}}
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP || exit 1
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$SOURCE \
-|| shellout "Extracting $SOURCE"
+tar xvf $CWD/$SOURCE
 
 introduce "Start SlackBuild $PRGNAM-$VERSION"
 test -d $PRGNAM-$VERSION || \
@@ -115,39 +122,44 @@ chmod -R u+w,go+r-w,a-s .
 #-perm 400 \) -exec chmod 644 {} \;
 
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-D_GNU_SOURCE -O2 -march=i486 -mtune=i686"
+    SLKCFLAGS="-D_GNU_SOURCE -O2 -march=i486 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-D_GNU_SOURCE -O2 -march=i686 -mtune=i686"
+    SLKCFLAGS="-D_GNU_SOURCE -O2 -march=i686 -mtune=i686"
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-D_GNU_SOURCE -O2 -fPIC"
-  LIBDIRSUFFIX="64"
-  NUMJOBS=2
+    SLKCFLAGS="-D_GNU_SOURCE -O2 -fPIC"
+    LIBDIRSUFFIX="64"
+    NUMJOBS=2
 fi
 
-introduce "Running configure"
+process="Running configure"
+introduce "$process"
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
---prefix=$PREFIX \
---libdir=$PREFIX/lib${LIBDIRSUFFIX} \
---sysconfdir=/etc \
---localstatedir=/var \
---mandir=$PREFIX/man \
---docdir=$PREFIX/doc/$PRGNAM-$VERSION \
---build=$ARCH-slackware-linux \
-|| shellout "configure of $PRGNAM-$VERSION failed"
+    --prefix=$PREFIX \
+    --libdir=$PREFIX/lib${LIBDIRSUFFIX} \
+    --sysconfdir=/etc \
+    --localstatedir=/var \
+    --mandir=$PREFIX/man \
+    --docdir=$PREFIX/doc/$PRGNAM-$VERSION \
+    --build=$ARCH-slackware-linux
 conclude "./configure finished successfully"
 
-introduce "Running make"
-make -j${NUMJOBS} || shellout "make failed." 
-introduce "Running make install"
-make DESTDIR=$PKG install || shellout "make install failed"
+process="Running make"
+introduce "$process"
+make -j${NUMJOBS}
+conclude "make finished successfully"
+
+process="Running make install"
+introduce "$process"
+make DESTDIR=$PKG install
+conclude "make install finished successfully"
 
 # strip binaries
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
 | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-# Installation of slack-desc
+# Installation of slack-desc#{{{
 mkdir -p $PKG/install 
 ( test -r $CWD/slack-desc && \
 cat $CWD/slack-desc > $PKG/install/slack-desc ) || \
@@ -160,7 +172,7 @@ cat << EODESC > $PKG/install/slack-desc
 # make exactly 11 lines for the formatting to be correct.  It's also           
 # customary to leave one space after the ':'.                                  
 
-         |-----handy-ruler----------------------------------------------------|
+|-----handy-ruler----------------------------------------------------|
 $PRGNAM:                                 ( $PRGNAM ) 
 $PRGNAM:
 $PRGNAM:
@@ -173,55 +185,62 @@ $PRGNAM:
 $PRGNAM: Packager: _PACKAGER on _BUILD_DATE
 $PRGNAM:
 EODESC
+##}}}
 
-# Install a doinst.sh, if it exists
+# Install a doinst.sh, if it exists#{{{
 if [ -r $CWD/doinst.sh ]; then
-   cat $CWD/doinst.sh > $PKG/install/doinst.sh
+    cat $CWD/doinst.sh > $PKG/install/doinst.sh
 fi
+##}}}
 
-## Install the manpages
-if [ -d $PKG/usr/man ]; then
-    cd $PKG/usr/man ;
+## Install the manpages#{{{
+if [ -d $PKG/$PREFIX/man ]; then
+    cd $PKG/$PREFIX/man ;
     find . -type f -exec gzip -9 {} \;
     for i in $( find . -type l ) ;do
         ln -s $( readlink $i ).gz $i.gz ; rm $i;
     done
 fi
+##}}}
 
-# Install the documentation
+# Install the documentation#{{{
 cd $TMP/$PRGNAM-$VERSION
 mkdir -p $PKG/$PREFIX/doc/$PRGNAM-$VERSION
 for i in $DOCS ;
 do 
-  if [ -r $i ]; then
-    install -m 644 $i $PKG/$PREFIX/doc/$PRGNAM-$VERSION
-  fi
+    if [ -r $i ]; then
+        install -m 644 $i $PKG/$PREFIX/doc/$PRGNAM-$VERSION
+    fi
 done
 
 mkdir -p  $PKG/$PREFIX/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/$PREFIX/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
+chown -R root:root $PKG/$PREFIX/doc/$PRGNAM-$VERSION
 find $PKG/$PREFIX/doc -type f -exec chmod 0644 {} \;
+##}}}
 
 # We change the default values in the slack-desc 
 sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 ${PKG}/install/slack-desc || true
 
 cd $PKG 
-introduce "Running makepkg ..."
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
-|| shellout "/sbin/makepkg for $PRGNAM-$VERSION failed"
+process="Running makepkg"
+introduce "$process"
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
 
+# Calculate the script time running !#{{{
 time_end=$(date +%s)
 elapsed_time_script=`expr $time_end - $time_start_script`
 #Convert seconds to h:m:s format
 _hms(){
-  local S=${1}
-  ((h=S/3600))
-  ((m=S%3600/60))
-  ((s=S%60))
-  printf "%dh:%dm:%ds\n" $h $m $s
+    local S=${1}
+    ((h=S/3600))
+    ((m=S%3600/60))
+    ((s=S%60))
+    printf "%dh:%dm:%ds\n" $h $m $s
 }
+##}}}
+
 conclude "The script has been running during $(_hms $elapsed_time_script)"
 conclude "Done ..."
 
diff --git a/pms-linux/pms-linux.SlackBuild b/pms-linux/pms-linux.SlackBuild
--- a/pms-linux/pms-linux.SlackBuild
+++ b/pms-linux/pms-linux.SlackBuild
@@ -32,12 +32,13 @@ DATE=$(LC_ALL=C date +%d-%b-%Y)
 PRGNAM=${PRGNAM:-pms-linux}
 SRCNAM=${SRCNAM:-$PRGNAM}
 SVN_URL=${SVN_URL:-http://ps3mediaserver.googlecode.com/svn/trunk/ps3mediaserver}
-SVN_VERSION=${SVN_VERSION:-$(wget -q -O- $SVN_URL/build.xml \
-| sed -n "s/^[[:space:]]\{1,\}<property[[:space:]]\{1,\}name=\"version\".*value=\"\([0-9.]\{1,\}\)\".*\/>$/\1/p")}
+SVN_VERSION=${SVN_VERSION:-$(wget -q -O - $SVN_URL/net/pms/PMS.java \
+| grep -E "public static final String VERSION"  \
+| sed -ne 's/^[^=]*.*= *\"\([0-9\.]\+\)\".*/\1/p')}
 SVN_REVISION=${SVN_REVISION:-$(svn log -q -r HEAD $SVN_URL \
 | awk '/^r[0-9][0-9]*/ { print $1 }')}
 VERSION=${SVN_VERSION}${SVN_REVISION}
-ARCH=${ARCH:-$(uname -m)}
+ARCH=${ARCH:-noarch}
 BUILD=${BUILD:-1}
 CWD=${CWD:-`pwd`}
 TMP=${TMP:-/tmp/SBp}
@@ -62,31 +63,35 @@ txtpur=$'\e[0;35m' # Purple
 txtcyn=$'\e[0;36m' # Cyan
 txtrst=$'\e[0m'    # Text Reset
 
+# Fancy functions#{{{
 frame()
 {
     WIDTH=78
-    STARS="++----------------------------------------------------------------------------+"
-    SPACES="                                                                               "
-    printf "%s\n" "${STARS:1:$WIDTH}"
+    STARS="+";for ((i=1; i<=$(($WIDTH-2)); i++));do STARS+="-";done; STARS+="+"
+    SPACES="";for ((i=1; i<$WIDTH; i++)); do SPACES+=" "; done
+    printf "%s\n" "${STARS:0:$WIDTH}"
     while read line ; do
         HALF="${SPACES:1:$((($WIDTH-${#line})/2))}"
         LINE="$HALF$line$SPACES"
         printf "+%s+\n" "${LINE:1:$(($WIDTH-2))}"
     done
-    printf "%s\n" "${STARS:1:$WIDTH}"
+    printf "%s\n" "${STARS:0:$WIDTH}"
 }
 introduce(){
-    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst \c "; sleep 2;
+    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst\c"; sleep 2;
 }
 conclude(){
     echo -e "${txtgrn}\n# $1 \n${txtrst}"; sleep 2;
 }
 shellout(){
-    echo -e "${txtred}Error:${txtrst} $1 ${txtcyn}(exit status -> $?)${txtrst}"; exit 1;
+  ret=$?
+    if (($ret)); then
+        echo -e "${txtred}Error:${txtrst} $process failed ! ${txtcyn}"
+    echo -e "(exit status of last command -> $ret)${txtrst}"
+      exit 1;
+    fi
 }
-warnout(){
-    echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
-}
+##}}}
 
 # Downloading the source
 if [ ! -r ${SRCNAM}-${VERSION}.$EXT ]; then
@@ -122,54 +127,48 @@ find . \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o \
 -perm 400 \) -exec chmod 644 {} \;
 
-# Let's backup PMS.conf too before modifying it !
-cp -a PMS.conf PMS.conf.example
-mv  PMS.sh pms-linux
+cp -a PMS.sh pms-linux
 
 # Let's change the original build.xml file
 # 1) We change the mode to 644
 # 2) We add new dirs of files to linux PACKAGE to be created during the build
 # 3) We include the new pms-linux (shell script) instead of the original one ( PMS.sh )
 mode=644
-add_to_build=dist-archive/**,PMS.conf,
-sed -i \
+add_to_build=dist-archive/**,PMS.conf,resources/**,
+sed -i".default" \
 -e "s/\(^[[:space:]]*<tarfileset.* mode=\"\).*\(\" prefix=.*\)/\1$mode\2/" \
 -e "s@\(^[[:space:]]*<tarfileset.* includes=\"\)\(.*\)@\1$add_to_build\2@" \
 -e "s@PMS.sh@pms-linux@" \
 build.xml || shellout "Changing build.xml file failed."
 
 # We change the DIRNAME variable of the default PMS.sh file
-sed -i -e \
-"s@\(^DIRNAME=\).*@\1/usr/share/$PRGNAM@" \
-pms-linux || exit 1
+sed -i -e "s@\(^DIRNAME=\).*@\1/usr/share/$PRGNAM@" pms-linux || exit 1
+# We add "cd $DIRNAME" into the PMS.sh (pms-linux) script.
+# DIRNAME is normally "/usr/share/pms-linux" 
+sed -i -e '/^DIRNAME=/ a\cd $DIRNAME' pms-linux || exit 1
 
-# Let's change an option in the PMS.conf file we will use for the system
-sed -i -e \
-"s/\(^minimized *= *\).*/\1true/" \
-PMS.conf || exit 1
-
-# Let's patch the TempFolder.java & PMS.java files
-cd $TMP/$PRGNAM-$VERSION/net/pms/configuration
-patch < $CWD/patches/TempFolder.java.diff \
-|| shellout "Patching TempFolder.java failed."
-
-cd $TMP/$PRGNAM-$VERSION/net/pms
-patch < $CWD/patches/PMS.java.diff \
-|| shellout "Patching PMS.java failed"
-## all patches done
+# Let's apply the patches
+cd $TMP/$PRGNAM-$VERSION
+patch -p1 <$CWD/patches/PMS.java.patch
+patch -p1 <$CWD/patches/TempFolder.java.patch
+patch -p1 <$CWD/patches/PmsConfiguration.java.patch
+patch -p1 <$CWD/patches/DLNAMediaDatabase.java.patch
+#patch -p1 <$CWD/patches/LinuxDefaultPaths.java.patch
 
 cd $TMP/$PRGNAM-$VERSION
-ant || shellout "Running of ant failed."
+ant || shellout "Running ant failed."
 ( cd $TMP/$PRGNAM-$VERSION/dist; tar xf *tgz; )
 
 mkdir -p $PKG/etc/{rc.d,logrotate.d}
 mkdir -p $PKG/usr/{bin,man/man1}
 mkdir -p $PKG/usr/share/{$PRGNAM,pixmaps,applications}
-mkdir -p $PKG/var/log/pms-linux
-chmod -R 1777 $PKG/var/log/pms-linux || exit 1
+mkdir -p $PKG/var/{lib,log}/pms-linux
+chmod -R 1777 $PKG/var/{lib,log}/pms-linux || exit 1
 
-cd $TMP/$PRGNAM-$VERSION/dist/$PRGNAM-$SVN_VERSION
+
+cd $TMP/$PRGNAM-$VERSION/dist/$PRGNAM-*
 cp -a renderers/ \
+resources \
 plugins/ \
 linux/ \
 dist-archive/ \
@@ -181,7 +180,7 @@ cat $TMP/$PRGNAM-$VERSION/WEB.conf > $PKG/etc/WEB.conf.new || exit 1
 
 chmod 0755 $PKG/usr/share/$PRGNAM/linux/tsMuxeR || exit 1
 
-install -m 0755 -D $TMP/$PRGNAM-$VERSION/dist/$PRGNAM-$SVN_VERSION/pms-linux \
+install -m 0755 -D $TMP/$PRGNAM-$VERSION/dist/$PRGNAM-*/pms-linux \
 $PKG/usr/bin || exit 1
 
 install -m 0755 $CWD/rc.pms-linux $PKG/etc/rc.d/rc.pms-linux.new || exit 1
@@ -227,9 +226,7 @@ fi
 
 # Install the documentation
 cd $TMP/$PRGNAM-$VERSION
-mkdir -p $PKG/$PREFIX/doc/$PRGNAM-$VERSION/examples
-install -m 0644 -D $TMP/$PRGNAM-$VERSION/{PMS.conf.example,WEB.conf} \
-$PKG/$PREFIX/doc/$PRGNAM-$VERSION/examples
+mkdir -p $PKG/$PREFIX/doc/$PRGNAM-$VERSION
 for i in $DOCS ;
 do 
   if [ -r $i ]; then
@@ -247,11 +244,9 @@ test -r $CWD/slack-desc && \
 cat $CWD/slack-desc > $PKG/install/slack-desc
 # -- finished install docs --
 
-set +e
 # We change the default values in the slack-desc 
 sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 ${PKG}/install/slack-desc
-set -e
 
 cd $PKG 
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
diff --git a/redmine/redmine.SlackBuild b/redmine/redmine.SlackBuild
--- a/redmine/redmine.SlackBuild
+++ b/redmine/redmine.SlackBuild
@@ -21,36 +21,39 @@
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 # Requirements:
-# Suggests: rake, rubygems
+# Suggests:
 
 time_start_script=$(date +%s)
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
-PACKAGER=${PACKAGER:-$USER@$(hostname -f)}
+PACKAGER=${PACKAGER:-$USER@$(cat /etc/HOSTNAME)}
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
 PRGNAM=${PRGNAM:-redmine}
 SRCNAM=${SRCNAM:-$PRGNAM}
-SVN_URL=${SVN_URL:-http://redmine.rubyforge.org/svn/trunk}
-SVN_REVISION=${SVN_REVISION:-"$(svn log -qr HEAD $SVN_URL | sed -n 's/^r\([0-9]\{1,\}\).*/\1/p')"}
-VERSION=${VERSION:-r$SVN_REVISION}
+VERSION=${VERSION:-1.0.4}
 ARCH=${ARCH:-noarch}
 BUILD=${BUILD:-1}
 CWD=${CWD:-`pwd`}
 TMP=${TMP:-/tmp/SBp}
 PKG=${PKG:-$TMP/package-$PRGNAM}
 OUTPUT=${OUTPUT:-/tmp}
-EXT=${EXT:-tar.bz2}
+EXT=${EXT:-tar.gz}
+SOURCE=${SRCNAM}-${VERSION}.$EXT
+URL=${URL:-http://rubyforge.org/frs/download.php/73457/$SOURCE}
 TAG=${TAG:-_paissad}
 PKGTYPE=${PKGTYPE:-tgz}
 RAILS_ROOT=${RAILS_ROOT:-/var/www/htdocs}
+PREFIX=${PREFIX:-"/usr"}
 NUMJOBS=${NUMJOBS:-}
 DOCS=${DOCS:-"CREDITS WHISHLIST ABOUT-NLS AUTHORS COPYING LICENSE* \
-CHANGELOG* ChangeLog* HACKING INSTALL* MAINTAINERS NEWS \
-ReadMe* README* THANKS TODO Todo RELEASE UPGRADING FAQ HELP*"}
+CHANGES CHANGELOG* ChangeLog* HACKING INSTALL* MAINTAINERS NEWS \
+ReadMe* README* THANKS TODO Todo RELEASE* UPGRADING* FAQ Faq HELP* BUGS*"}
 
 set -e
+trap shellout EXIT
 
+# Colors#{{{
 txtred=$'\e[0;31m' # Red
 txtgrn=$'\e[0;32m' # Green
 txtylw=$'\e[0;33m' # Yellow
@@ -58,63 +61,51 @@ txtblu=$'\e[0;34m' # Blue
 txtpur=$'\e[0;35m' # Purple
 txtcyn=$'\e[0;36m' # Cyan
 txtrst=$'\e[0m'    # Text Reset
+##}}}
 
+# Fancy functions#{{{
 frame()
 {
     WIDTH=78
-    STARS="++----------------------------------------------------------------------------+"
-    SPACES="                                                                               "
-    printf "%s\n" "${STARS:1:$WIDTH}"
+    STARS="+";for ((i=1; i<=$(($WIDTH-2)); i++));do STARS+="-";done; STARS+="+"
+    SPACES="";for ((i=1; i<$WIDTH; i++)); do SPACES+=" "; done
+    printf "%s\n" "${STARS:0:$WIDTH}"
     while read line ; do
         HALF="${SPACES:1:$((($WIDTH-${#line})/2))}"
         LINE="$HALF$line$SPACES"
         printf "+%s+\n" "${LINE:1:$(($WIDTH-2))}"
     done
-    printf "%s\n" "${STARS:1:$WIDTH}"
+    printf "%s\n" "${STARS:0:$WIDTH}"
 }
 introduce(){
-    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst \c "; sleep 2;
+    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst\c"; sleep 2;
 }
 conclude(){
     echo -e "${txtgrn}\n# $1 \n${txtrst}"; sleep 2;
 }
 shellout(){
-    echo -e "${txtred}Error:${txtrst} $1 ${txtcyn}(exit status -> $?)${txtrst}"; exit 1;
+	ret=$?
+    if (($ret)); then
+        echo -e "${txtred}Error:${txtrst} $process failed ! ${txtcyn}"
+		echo -e "(exit status of last command -> $ret)${txtrst}"
+	   	exit 1;
+    fi
 }
-warnout(){
-    echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
-}
+##}}}
 
-# Determine the tarball extension:
-case "$EXT" in
-    "tar.xz") TARCOMP="J" ;;
-    "tar.gz") TARCOMP="z" ;;
-    "tgz") TARCOMP="z" ;;
-    "tar.bz2") TARCOMP="j" ;;
-    *) echo "Archive can only have extension 'tar.xz', '.tar.gz' '.tar.bz2' or '.tgz'" ; 
-    exit 1 ;;
-esac
-
-# Download of the source !
-if [ ! -r ${SRCNAM}-${VERSION}.$EXT ]; then
-    introduce "Start downloading ${SRCNAM} at revision $SVN_REVISION" 
-    svn export -r $SVN_REVISION $SVN_URL $PRGNAM-$VERSION  \
-  || shellout "Downloading ${SRCNAM}"
-    conclude "Download of ${SRCNAM} at revision $SVN_REVISION finished successfully !"
-
-  introduce "Compressing source ..."
-    tar -${TARCOMP}cvf $PRGNAM-$VERSION.$EXT $PRGNAM-$VERSION \
-    || shellout "Compressing source failed."
-    conclude "Compressing source finished successfully."
-    conclude "The file is $SRCNAM-$VERSION.$EXT" 
+# Download of the source !#{{{
+if [[ ! -r "$SOURCE" ]]; then
+    introduce "Start downloading $SOURCE" 
+    wget "$URL"
+    conclude "Download of $SOURCE finished successfully !"
 fi
+##}}}
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP || exit 1
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/${SRCNAM}-${VERSION}.$EXT \
-|| shellout "Extracting ${SRCNAM}-${VERSION}.$EXT"
+tar xvf $CWD/$SOURCE
 
 introduce "Start SlackBuild $PRGNAM-$VERSION"
 test -d $PRGNAM-$VERSION || \
@@ -136,15 +127,19 @@ fi
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
-mkdir -p $PKG/$RAILS_ROOT
+mkdir -p $PKG/$RAILS_ROOT/
 cp -a $TMP/$PRGNAM-$VERSION/ $PKG/$RAILS_ROOT/$PRGNAM
+
 mv $PKG/$RAILS_ROOT/$PRGNAM/config/database.yml.example $PKG/$RAILS_ROOT/$PRGNAM/config/database.yml.new
 mv $PKG/$RAILS_ROOT/$PRGNAM/config/email.yml.example $PKG/$RAILS_ROOT/$PRGNAM/config/email.yml.new
 
-chown -R redmine:redmine $PKG/$RAILS_ROOT/$PRGNAM/{files,log,tmp}
-chmod -R 755 $PKG/$RAILS_ROOT/$PRGNAM/{files,log,tmp}
+mkdir -p $PKG/$RAILS_ROOT/$PRGNAM/public/plugin_assets
+chown -R redmine:redmine $PKG/$RAILS_ROOT/$PRGNAM/{files,public/plugin_assets,log,tmp}
+chmod -R 755 $PKG/$RAILS_ROOT/$PRGNAM/{files,public/plugin_assets,log,tmp}
 
-# Installation of slack-desc
+#chmod 0600 $PKG/$RAILS_ROOT/$PRGNAM/config{database.yml.new,email.yml.new} 
+
+# Installation of slack-desc#{{{
 mkdir -p $PKG/install 
 ( test -r $CWD/slack-desc && \
 cat $CWD/slack-desc > $PKG/install/slack-desc ) || \
@@ -170,30 +165,42 @@ redmine:
 redmine: Packager: _PACKAGER on _BUILD_DATE
 redmine:
 EODESC
+##}}}
 
-# Install a doinst.sh, if it exists
+# Install a doinst.sh, if it exists#{{{
 if [ -r $CWD/doinst.sh ]; then
-   cat $CWD/doinst.sh > $PKG/install/doinst.sh
+    cat $CWD/doinst.sh > $PKG/install/doinst.sh
 fi
+##}}}
 
 # Let's remove the 1st & last / of the $RAILS_ROOT variable
-RAILS_ROOT=$( echo $RAILS_ROOT | sed -e "s,^/,," -e "s,/$,,")
+RAILS_ROOT=$(echo $RAILS_ROOT | sed -e "s,^/,," -e "s,/$,,")
 
 # add .new files to doinst.sh file
 echo "config $RAILS_ROOT/$PRGNAM/config/database.yml.new" >> $PKG/install/doinst.sh
 echo "config $RAILS_ROOT/$PRGNAM/config/email.yml.new" >> $PKG/install/doinst.sh
 echo -e "\nrm -rf $RAILS_ROOT/tmp/cache/*" >> $PKG/install/doinst.sh
 
-# Install the documentation
-PREFIX=usr
+## Install the manpages#{{{
+if [ -d $PKG/usr/man ]; then
+    cd $PKG/usr/man ;
+    find . -type f -exec gzip -9 {} \;
+    for i in $( find . -type l ) ;do
+        ln -s $( readlink $i ).gz $i.gz ; rm $i;
+    done
+fi
+##}}}
+
+# Install the documentation#{{{
 cd $TMP/$PRGNAM-$VERSION
 mkdir -p $PKG/$PREFIX/doc/$PRGNAM-$VERSION
-for i in $DOCS doc/* ;
+for i in $DOCS ;
 do 
-  if [ -r $i ]; then
-    install -m 644 $i $PKG/$PREFIX/doc/$PRGNAM-$VERSION
-  fi
+    if [ -r $i ]; then
+        install -m 644 $i $PKG/$PREFIX/doc/$PRGNAM-$VERSION
+    fi
 done
+##}}}
 
 mkdir -p  $PKG/$PREFIX/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/$PREFIX/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
@@ -205,20 +212,23 @@ sed -i "s|_PACKAGER|${PACKAGER}|g; s|_BUILD_DATE|${DATE}|g" \
 ${PKG}/install/slack-desc || true
 
 cd $PKG 
-introduce "Running makepkg ..."
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
-|| shellout "/sbin/makepkg for $PRGNAM-$VERSION failed"
+process="Running makepkg"
+introduce "$process"
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
 
+# Calculate the script time running !#{{{
 time_end=$(date +%s)
 elapsed_time_script=`expr $time_end - $time_start_script`
 #Convert seconds to h:m:s format
 _hms(){
-  local S=${1}
-  ((h=S/3600))
-  ((m=S%3600/60))
-  ((s=S%60))
-  printf "%dh:%dm:%ds\n" $h $m $s
+    local S=${1}
+    ((h=S/3600))
+    ((m=S%3600/60))
+    ((s=S%60))
+    printf "%dh:%dm:%ds\n" $h $m $s
 }
+##}}}
+
 conclude "The script has been running during $(_hms $elapsed_time_script)"
 conclude "Done ..."
 
