NEW     : * vlc, modplugtools, xbmc, bastille, x264, pulseaudio,             floodmon, libbluray, libmodplug, goom, oci8, openldap,             mediawiki, numactl, xtables-addons, MPlayer. CHANGES : * kernel (the build is now done in /usr/src)             postfix (new version of the software)             dovecot (new version of software)             partimage (new rc.d start script, the SlackBuild handles             user and group to run partimage, certificates ...)             ffmpeg ( some features where removed in the ./configure since             they are no longer availaible ...) BUGFIX  : * wordpress (i used cp instead of mv in order to create a conf file             wp-config.php.new .... that's bad for the doinst.sh script ... Now,             i definitely use mv)
git-svn-id: https://svn.paissad.net/slackbuilds/stable@13 a8e915ae-7a13-4794-ad7b-daf03aeeedbb

diff --git a/dovecot/dovecot.SlackBuild b/dovecot/dovecot.SlackBuild
--- a/dovecot/dovecot.SlackBuild
+++ b/dovecot/dovecot.SlackBuild
@@ -20,16 +20,66 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+time_start_script=$(date +%s)
+
 PRGNAM="dovecot"
+SRCNAM=${SRCNAM:-$PRGNAM}
 VERSION="1.1.15"
 ARCH=${ARCH:-$(uname -m)}
-BUILD=${BUILD:-2}
+BUILD=${BUILD:-3}
 TAG=${TAG:-_paissad}
+
+EXT=${EXT:-tar.gz}
+SOURCE=${SRCNAM}-${VERSION}.$EXT
+URL=${URL:-http://www.dovecot.org/releases/1.1/$SOURCE}
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/SBp}
 PKG="$TMP/package-$PRGNAM"
 OUTPUT=${OUTPUT:-/tmp}
+
+set -e
+
+txtred=$'\e[0;31m' # Red
+txtgrn=$'\e[0;32m' # Green
+txtylw=$'\e[0;33m' # Yellow
+txtblu=$'\e[0;34m' # Blue
+txtpur=$'\e[0;35m' # Purple
+txtcyn=$'\e[0;36m' # Cyan
+txtrst=$'\e[0m'    # Text Reset
+
+frame()
+{
+    WIDTH=78
+    STARS="++----------------------------------------------------------------------------+"
+    SPACES="                                                                               "
+    printf "%s\n" "${STARS:1:$WIDTH}"
+    while read line ; do
+        HALF="${SPACES:1:$((($WIDTH-${#line})/2))}"
+        LINE="$HALF$line$SPACES"
+        printf "+%s+\n" "${LINE:1:$(($WIDTH-2))}"
+    done
+    printf "%s\n" "${STARS:1:$WIDTH}"
+}
+introduce(){
+    echo -e "$txtgrn"; printf "$1\n" | frame; echo -e "$txtrst \c "; sleep 2;
+}
+conclude(){
+    echo -e "${txtgrn}\n# $1 \n${txtrst}"; sleep 2;
+}
+shellout(){
+    echo -e "${txtred}Error:${txtrst} $1 ${txtcyn}(exit status -> $?)${txtrst}"; exit 1;
+}
+warnout(){
+    echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
+}
+
+# Download of the source !
+if [ ! -r $SOURCE ]; then
+    introduce "Start downloading $SOURCE" 
+    wget "$URL" || shellout "Downloading $SOURCE"
+    conclude "Download of $SOURCE finished successfully !"
+fi
 
 # Bail if user isn't valid on your system
 if ! grep -q ^dovecot: /etc/passwd ; then
@@ -39,8 +89,6 @@ if ! grep -q ^dovecot: /etc/passwd ; then
   echo "  Or something similar."
   exit 1
 fi
-
-set -e
 
 if [ "$ARCH" = "i486" ]; then
   SLKCFLAGS="-O2 -march=i486 -mtune=i686"
@@ -106,3 +154,17 @@ cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+
+time_end=$(date +%s)
+elapsed_time_script=`expr $time_end - $time_start_script`
+#Convert seconds to h:m:s format
+_hms(){
+  local S=${1}
+  ((h=S/3600))
+  ((m=S%3600/60))
+  ((s=S%60))
+  printf "%dh:%dm:%ds\n" $h $m $s
+}
+conclude "The script has been running during $(_hms $elapsed_time_script)"
+conclude "Done ..."
+
diff --git a/kernel/kernel.SlackBuild b/kernel/kernel.SlackBuild
--- a/kernel/kernel.SlackBuild
+++ b/kernel/kernel.SlackBuild
@@ -26,27 +26,30 @@
 time_start_script=$(date +%s)
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
-PACKAGER=${PACKAGER:-$USER@$(hostname)}
+PACKAGER=${PACKAGER:-$USER@$(hostname -f)}
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
 PRGNAM=${PRGNAM:-kernel}
 SRCNAM=${SRCNAM:-linux}
-KERN_NAME=${KERN_NAME:-huge}  # Usually huge or generic, but you may chose what you want
-MAIN_KERNEL="v2.6"    # Normally you do not need to change this !
-KERN_CONFIG=${KERN_CONFIG:-menuconfig}   # Ex: silentoldconfig, menuconfig ...
-RUN_KERN_CONFIG=${RUN_KERN_CONFIG:-no} # set to "yes" if you want to run the config in any cases 
-BUILD_DOCS=${BUILD_DOCS:-no}  # change to "yes" if you want to build docs 
-VERSION=${VERSION:-auto}  # if 'auto', the SlackBuild will retreive latest stable kernel 
+KERN_NAME=${KERN_NAME:-huge} # Usually huge or generic, but you may choose what you want
+MAIN_KERNEL="v2.6"           # Normally you do not need to change this !
+KERN_CONFIG=${KERN_CONFIG:-oldconfig} # Ex: silentoldconfig, menuconfig, xconfig ...
+RUN_KERN_CONFIG=${RUN_KERN_CONFIG:-yes} # set to "yes" if you want to run the config in any cases 
+BUILD_DOCS=${BUILD_DOCS:-no}            # change to "yes" if you want to build docs 
+VERSION=${VERSION:-auto}                # if 'auto', the SlackBuild will retreive latest stable kernel 
 APPLY_PATCH=${APPLY_PATCH:-no}
-PATCH=${PATCH:-}           # example: if VERSION=2.6.32 and PATCH=3 you will have 2.6.32.3,
-ARCH=${ARCH:-$(uname -m)}      # Just do VERSION=2.6.32.3 (easier). If you use VERSION=auto, then you
-BUILD=${BUILD:-1}              # obviously don't need to have a patch since latest version has no patch 
+PATCH=${PATCH:-} # example: if VERSION=2.6.32 and PATCH=3 you will have 2.6.32.3,
+                 # Just do VERSION=2.6.32.3 (easier). If you use VERSION=auto, then you
+                 # obviously don't need to have a patch since latest version has no patch 
+ARCH=${ARCH:-$(uname -m)}
+BUILD=${BUILD:-1}
 CWD=${CWD:-`pwd`}
+KBUILDDIR=${KBUILDDIR:-/usr/src}
 TMP=${TMP:-/tmp/SBp}
 PKG=${PKG:-$TMP/package-$PRGNAM}
 OUTPUT=${OUTPUT:-/tmp}
-SHORT_EXT=${SHORT_EXT:-bz2}   # gz or bz2
-EXT=${EXT:-tar.$SHORT_EXT}  # Do not change this ... unless you know what you do
+SHORT_EXT=${SHORT_EXT:-bz2} # gz or bz2
+EXT=${EXT:-tar.$SHORT_EXT} 
 SHORT_URL=${SHORT_URL:-http://www.kernel.org/pub/linux/kernel/$MAIN_KERNEL}
 TAG=${TAG:-_paissad}
 PKGTYPE=${PKGTYPE:-tgz}
@@ -57,14 +60,16 @@ THANKS TODO RELEASE UPGRADING FAQ HELP"}
 
 set -e
 
+# Colors#{{{
 txtred=$'\e[0;31m' # Red
 txtgrn=$'\e[0;32m' # Green
 txtylw=$'\e[0;33m' # Yellow
 txtblu=$'\e[0;34m' # Blue
 txtpur=$'\e[0;35m' # Purple
 txtcyn=$'\e[0;36m' # Cyan
-txtrst=$'\e[0m'    # Text Reset
+txtrst=$'\e[0m'    # Text Reset#}}}
 
+# Fancy functions to make the sript more user friendly ...#{{{
 frame()
 {
     WIDTH=78
@@ -90,7 +95,9 @@ shellout(){
 warnout(){
     echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
 }
+##}}}
 
+# Grab latest kernel version#{{{
 LATEST_KERNEL=$(wget -q $SHORT_URL -O - \
 | grep LATEST-IS \
 | tail -n 1 \
@@ -100,8 +107,9 @@ LATEST_KERNEL=$(wget -q $SHORT_URL -O - \
 if [ $VERSION = auto ]; then
       VERSION=$LATEST_KERNEL 
 fi
+##}}}
 
-# Fancy function to create a progress bar ( i will use it for tar xvf btw )
+# Fancy function to create a progress bar ( i will use it for tar xvf ... )#{{{
 # The function takes one argument, which is the action to "progress bar"
 # This progress bar works only for tar program
 progress_bar(){
@@ -125,23 +133,26 @@ $1 | while read ; do
 done
 echo
 }
+##}}}
 
 URL=$SHORT_URL/$SRCNAM-$VERSION.$EXT
 URL_TESTING=$SHORT_URL/testing/$SRCNAM-$VERSION.$EXT
 
-## Let's check if the kernel specified does exit in www.kernel.org
+## Let's check if the specified kernel does exit in www.kernel.org#{{{
 ## I just try to download the ChangeLog file, if it succeeds, that's good !
 ( wget -q "$SHORT_URL/ChangeLog-$VERSION" -O /dev/null \
 && echo "kernel -> OK." ) \
 || ( wget -q "$SHORT_URL/testing/ChangeLog-$VERSION" -O /dev/null \
 &&  echo "kernel -> OK." ) \
 || warnout "It's almost sure that the kernel you specified does not exist !!!
-         And probably, the download will fail"
+         And probably, the download will fail."
+##}}}
 
 # If we give a value to patch version to retreive,
 # then we change APPLY_PATCH to value "yes" !!
 test -z $PATCH || APPLY_PATCH=yes
 
+# Print some informations#{{{
 print_info(){
 echo
 echo -e ""$txtgrn"Your distribution is....:"$txtcyn" $(cat /etc/slackware-version || exit 0)"
@@ -153,38 +164,43 @@ echo -e ""$txtgrn"Applying a patch .......:"$txtcyn" version of patch -> ($APPLY
 echo -e ""$txtgrn"Building kernel docs ...:"$txtcyn" ($BUILD_DOCS)"
 echo -e "$txtrst" ; sleep 5;
 }
+##}}}
 print_info
 
 # ============================================================================
 # ==============          LET'S PREPARE THE WORK :-)           ===============
 # ============================================================================
 
-# Download of the source !
+# Download of the source !#{{{
 if [ ! -r ${SRCNAM}-${VERSION}.$EXT ]; then
     introduce "Start downloading ${SRCNAM}-${VERSION}.$EXT" 
     wget "$URL" || wget "$URL_TESTING" \
   || shellout "Downloading ${SRCNAM}-${VERSION}.$EXT"
     conclude "Download of ${SRCNAM}-${VERSION}.$EXT finished successfully !"
 fi
+##}}}
 
-# We import the public key
+# We import the public key#{{{
 introduce "Importing public key of kernel.org"
 gpg --keyserver wwwkeys.pgp.net --recv-keys 0x517D0F0E \
 || shellout "importing public key failed."
 conclude "importing public key finished successfully."
+##}}}
 
-## We download signature of the source. 
+## We download signature of the source. #{{{
 introduce "Downloading signature for this kernel"
 wget -c "$URL.sign" || wget -c "$URL_TESTING.sign" \
 || shellout "Donwloading gpg public key"
 conclude "Signature download finished successfully."
+##}}}
 
-# We verify the source.
+# We verify the source.#{{{
 introduce "Verifying source with public gpg key"
 gpg --verify "$SRCNAM-$VERSION.$EXT.sign" "$SRCNAM-$VERSION.$EXT" \
 || shellout "gpg --verify failed for $SRCNAM-$VERSION.$EXT" 
+##}}}
 
-# Download of the patch if specified
+# Download of the patch if specified#{{{
 if [ $APPLY_PATCH = yes ]; then
     introduce "Downloading patch-$VERSION.$PATCH.$SHORT_EXT"
     wget -c $SHORT_URL/patch-$VERSION.$PATCH.$SHORT_EXT \
@@ -201,30 +217,32 @@ if [ $APPLY_PATCH = yes ]; then
     || shellout "Verification of the patch failed."
     conclude "Signature of the patch downloaded & verified successfully."
 fi
-# -- End of patch stuff ! ------------
-
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-cd $TMP || exit 1
-rm -rf $PRGNAM-$VERSION
-
-# Extraction of the source
-introduce "Extracting kernel source ( $SRCNAM-$VERSION.$EXT )"
-progress_bar "tar xvf $CWD/${SRCNAM}-${VERSION}.$EXT" \
-|| shellout "Extracting kernel failed."
-conclude "Kernel extraction finished successfully ..."
+##}}}
 
 # ============================================================================
 # ==============          LET'S BEGIN THE REAL WORK :-)        ===============
 # ============================================================================
 
+test ! -d $KBUILDDIR/${SRCNAM}-${VERSION} \
+|| warnout "$KBUILDDIR/${SRCNAM}-${VERSION} does already exist.\n\
+You should remove that dir or change your \$KBUILDDIR variable.to so that you \
+use another directory."
+
+rm -rf $PKG
+mkdir -p $TMP $PKG $OUTPUT
+cd $KBUILDDIR
+
+# Extraction of the source#{{{
+introduce "Extracting kernel source ( $SRCNAM-$VERSION.$EXT )"
+progress_bar "tar xvf $CWD/${SRCNAM}-${VERSION}.$EXT" \
+|| shellout "Extracting kernel failed."
+conclude "Kernel extraction finished successfully ..."
+##}}}
+
 introduce "Start SlackBuild $PRGNAM-$VERSION"
 
-test -d $PRGNAM-$VERSION || \
-mv -v ${SRCNAM}-${VERSION} $PRGNAM-$VERSION
-cd $TMP/$PRGNAM-$VERSION
-
-# patch the tree if specified ! 
+cd $KBUILDDIR/$SRCNAM-$VERSION
+# patch the tree if specified ! #{{{
 if [ $APPLY_PATCH = yes ]; then
         introduce "Applying patch -> $PATCH"
    if [ $SHORT_EXT = bz2 ]; then
@@ -237,12 +255,16 @@ if [ $APPLY_PATCH = yes ]; then
    VERSION+=.$PATCH
    conclude "Patch ( $PATCH ) applied successfully.\nAnd the new version of the package is then $VERSION"
 fi
+##}}}
 
-previous_config=
-if [ -f $CWD/config-$VERSION ]; then 
+# Retreive the previous kernel config#{{{
+previous_config=""
+if [ -f $CWD/config-$VERSION ]; then
+	echo "Using '$CWD/config-$VERSION' for kernel configuration"; sleep 3;
     previous_config=$CWD/config-$VERSION
     cat $previous_config > .config
 elif [ -f /proc/config.gz ]; then
+	echo "Using current system kernel configuration"; sleep 3;
     zcat /proc/config.gz > .config
 	config_tmp=config.`uname -r`
     cat .config > $config_tmp
@@ -254,16 +276,50 @@ else
 fi
 
 if [ "$RUN_KERN_CONFIG" =  "yes" ]; then
-        make $KERN_CONFIG || shellout "make $KERN_CONFIG failed."
+	case $KERN_CONFIG in
+		oldconfig|silentoldconfig)
+        # avoid entering ENTER manually !
+		while echo; do :; done | make $KERN_CONFIG || shellout "make $KERN_CONFIG failed."
+		#make $KERN_CONFIG || shellout "make $KERN_CONFIG failed"
+        #
+        # Uncomment the following if you want to run make menuconfig after the
+        # run of 'make oldconfig' or 'make silentoldconfig'
+		#make menuconfig || shellout "make menuconfig failed."
+		;;
+		*)
+		make $KERN_CONFIG || shellout "make $KERN_CONFIG failed."
+		;;
+	esac
 fi
+##}}}
 
-# Let's create the diff file about 2 kernel config files. 
+# Let's create the diff file about 2 kernel config files. #{{{
 if [ "x$previous_config" != "x" ]; then
     diff -U 0 $previous_config .config > $CWD/config.diff || true 
     rm -f $config_tmp # this file may not exist before :)
 fi
+##}}}
 
 # ============= PACKAGING ================= #
+
+CONFIG_LOCALVERSION=$(sed -n "s/^CONFIG_LOCALVERSION=\"\(.*\)\"$/\1/p" $KBUILDDIR/$SRCNAM-$VERSION/.config)
+SMALL_VERSION=$VERSION
+VERSION+=$CONFIG_LOCALVERSION
+
+if [ "x$CONFIG_LOCALVERSION" != "x" ]; then
+echo -e "${txtblu}\nKnowing that you set CONFIG_LOCALVERSION in your kernel config,\
+\nthe new version is ${VERSION}\n"; sleep 5;
+
+# CONFIG_LOCALVERSION should not contain some character like '-' for example
+# Indeed, that could break the slack-desc even if the build will be ok !
+warning_chars=$(echo $CONFIG_LOCALVERSION | sed  "s/[a-zA-Z0-9\._+]//g")
+if [ "x$warning_chars" != "x" ]; then
+warnout "You should not use these characters [$warning_chars] in your kernel config \
+\nCONFIG_LOCALVERSION, you should only use alphanumeric characters and the dot '.' "
+sleep 5
+fi
+
+fi
 
 PACKAGING="$KERN_NAME modules headers firmware source "
 if [ $BUILD_DOCS = yes ]; then
@@ -278,15 +334,16 @@ PKGFIRM=$PKG/kernel-firmware
 PKGDOCS=$PKG/kernel-docs
 
 if [ "$ARCH" = "x86_64" ]; then
-        NUMJOBS=2;
+        NUMJOBS=${NUMJOBS:-$(grep -c ^processor /proc/cpuinfo 2> /dev/null)}
 fi
 
-introduce "Running target ** make all -j$NUMJOBS **"
+introduce "Running target 'all' ** make all -j$NUMJOBS **"
 make all -j ${NUMJOBS} || shellout "make all -j $NUMJOBS failed."
 
-introduce "Running target ** modules_prepare **"
+introduce "Running target 'modules_prepare'"
 make modules_prepare || shellout "make modules_prepare failed."
 
+# Install kernel #{{{
 mkdir -p $PKGKERN/boot 
 mkdir -p $PKGKERN/install
 cp arch/x86/boot/bzImage System.map $PKGKERN/boot/ || exit 1
@@ -294,50 +351,56 @@ chmod 0644 $PKGKERN/boot/* || exit 1
 cat .config > $PKGKERN/boot/config-$KERN_NAME-$VERSION || exit 1
 mv $PKGKERN/boot/{bzImage,vmlinuz-$KERN_NAME-$VERSION} || exit 1
 mv $PKGKERN/boot/{System.map,System.map-$KERN_NAME-$VERSION} || exit 1
-cd $PKGKERN/boot || exit 1
-ln -sf vmlinuz-$KERN_NAME-$VERSION vmlinuz || exit 1
-ln -sf System.map-$KERN_NAME-$VERSION System.map || exit 1
-ln -sf config-$KERN_NAME-$VERSION config  || exit 1
+cd $PKGKERN/boot
+ln -sf vmlinuz-$KERN_NAME-$VERSION vmlinuz
+ln -sf System.map-$KERN_NAME-$VERSION System.map
+ln -sf config-$KERN_NAME-$VERSION config
 conclude "Building & installing kernel image finished successfully."
+##}}}
 
-# Install kernel headers
-introduce "Running target ** headers_install **"
-cd $TMP/$PRGNAM-$VERSION
+# Install kernel headers#{{{
+introduce "Running target 'headers_install'"
+cd $KBUILDDIR/$SRCNAM-$SMALL_VERSION
 mkdir -p $PKGHEAD/install
 make -j $NUMJOBS headers_install INSTALL_HDR_PATH=$PKGHEAD/usr \
 || shellout "make headers_install failed."
 conclude "Building & installing  headers finished successfully."
+##}}}
 
-# Install modules 
-introduce "Running target ** modules_install **"
+# Install modules #{{{
+introduce "Running target 'modules_install'"
 mkdir -p $PKGMOD/install
-cd $TMP/$PRGNAM-$VERSION
+cd $KBUILDDIR/$SRCNAM-$SMALL_VERSION
 make -j $NUMJOBS modules_install INSTALL_MOD_PATH=$PKGMOD \
 || shellout "make modules_install failed."
-# Let's compress modules ...
+# Let's compress the modules ...
 # (
 #    cd $PKGMOD/lib/modules/$VERSION/kernel
-#    find . -name "*.ko" -exec gzip {} \;
+#    find . -type f -name "*.ko" -exec gzip {} \;
 # )
-# Let's remove the default symlinks (we will create the in the slack-desc)
-cd $PKGMOD/lib/modules/$VERSION
+# Let's remove the default symlinks (we will create it in the doinst.sh file)
+cd $PKGMOD/lib/modules/${VERSION}
 rm -f source build
+# We remove the firwwares because they will handled in another package
+# which is kernel-firmware ...
+rm -rf $PKGMOD/lib/firmware/
 conclude "Building & installing modules finished successfully."
+##}}}
 
-# Install firmwares
-introduce "Running target ** firmware_install **"
+# Install firmwares#{{{
+introduce "Running target 'firmware_install'"
 mkdir -p $PKGFIRM/lib/firmware
 mkdir -p $PKGFIRM/install
-cd $TMP/$PRGNAM-$VERSION
+cd $KBUILDDIR/$SRCNAM-$SMALL_VERSION
 make -j $NUMJOBS firmware_install INSTALL_FW_PATH=$PKGFIRM/lib/firmware \
 || shellout "make firmware_install failed."
 conclude "Building & installing firmwares finished successfully."
 
 ## Build docs ( if specified )
 if [ "$BUILD_DOCS" = "yes" ]; then
-   introduce "Running target ** mandocs **"
+   introduce "Running target 'mandocs'"
    mkdir -p $PKGDOCS/install
-   cd $TMP/$PRGNAM-$VERSION
+   cd $KBUILDDIR/$SRCNAM-$SMALL_VERSION
    make -j $NUMJOBS mandocs || shellout "make mandocs failed."
    # Install docs
    # Let's change the emplacement where docs will be installed.
@@ -348,19 +411,20 @@ if [ "$BUILD_DOCS" = "yes" ]; then
    find $PKGDOCS -type f -exec chmod 0644 {} \;
    conclude "Building & installing mandocs finished successfully."
 fi
+##}}}
 
-# Install source 
-introduce "Running target ** clean ** & install source"
+# Install source #{{{
+introduce "Installing the kernel source"
 mkdir -p $PKGSRC/usr/src
 mkdir -p $PKGSRC/install
-make clean || shellout "make clean failed."
-cp -a $TMP/$PRGNAM-$VERSION $PKGSRC/usr/src/linux-$VERSION \
+cp -a $KBUILDDIR/$SRCNAM-$SMALL_VERSION $PKGSRC/usr/src/linux-$VERSION \
 || shellout "Copying source files failed."
 cd $PKGSRC/usr/src
 ln -sf linux-$VERSION linux
 conclude "Building & installing firmwares finished successfully."
+##}}}
 
-# Installation of all slack-desc files.
+# Installation of all slack-desc files.#{{{
 ( test -r $CWD/slack-desc.$KERN_NAME && \
 cat $CWD/slack-desc.$KERN_NAME > $PKGKERN/install/slack-desc ) || \
 cat << EODESC > $PKGKERN/install/slack-desc
@@ -403,8 +467,9 @@ do
        ${PKG}/kernel-$i/install/slack-desc || true
    fi
 done
+##}}}
 
-# Install a doinst.sh, if it exists
+# Install a doinst.sh, if it exists#{{{
 for i in $PACKAGING;
 do
     if [ -r $CWD/doinst.sh.$i ]; then
@@ -420,51 +485,58 @@ cat <<EOFDOINST >> $PKGMOD/install/doinst.sh
 ( cd lib/modules/$VERSION ; ln -sf /usr/src/linux-$VERSION source )
 /sbin/depmod -a
 EOFDOINST
+##}}}
 
 # ================= Let's create the packages =================== #
 
-### packaging kernel-$KERN_NAME
+### packaging kernel-$KERN_NAME#{{{
 (
     cd $PKGKERN
     chown -R root.root . ;
   /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$KERN_NAME-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
   || shellout "makepkg failed for $PKGKERN" ;
 )
-### packaging kernel-modules
+##}}}
+### packaging kernel-modules#{{{
 (
     cd $PKGMOD
     chown -R root.root . ;
   /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-modules-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
   || shellout "makepkg failed for $PKGMOD" ;
 )
-### packaging kernel-headers
+##}}}
+### packaging kernel-headers#{{{
 (
     cd $PKGHEAD
     chown -R root.root . ;
   /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-headers-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE \
   || shellout "makepkg failed for $PKGHEAD" ;
 )
-### packaging kernel-firmware
+##}}}
+### packaging kernel-firmware#{{{
 (
     cd $PKGFIRM
     chown -R root.root . ;
   /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-firmware-$VERSION-noarch-$BUILD$TAG.$PKGTYPE \
   || shellout "makepkg failed for $PKGFIRM" ;
 )
-### packaging kernel-source
+##}}}
+### packaging kernel-source#{{{
 (
     cd $PKGSRC
     chown -R root.root . ;
   /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-source-$VERSION-noarch-$BUILD$TAG.$PKGTYPE \
   || shellout "makepkg failed for $PKGSRC" ;
 )
-### packaging docs 
+##}}}
+### packaging docs #{{{
 if [ "$BUILD_DOCS" = "yes" ]; then
    cd $PKGDOCS
    chown -R root.root . 
    /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-docs-$VERSION-noarch-$BUILD$TAG.$PKGTYPE \
    || shellout "makepkg failed for $PKGDOCS" 
 fi
+##}}}
 
 time_end=$(date +%s)
 elapsed_time_script=`expr $time_end - $time_start_script`
@@ -477,11 +549,23 @@ _hms(){
   printf "%dh:%dm:%ds\n" $h $m $s
 }
 conclude "The script has been running during $(_hms $elapsed_time_script)"
+
+if [ -d ${KBUILDDIR}/${SRCNAM}-${SMALL_VERSION} ]; then
+cat <<_EOT_
+Now that the build finished successfully, you can and should remove the
+directory ${KBUILDDIR}/${SRCNAM}-${SMALL_VERSION}.
+You can reinstall it using the $PRGNAM-source-$VERSION-noarch-$BUILD$TAG.$PKGTYPE
+package.
+It's absolutely the same !
+_EOT_
+
+fi
+
 conclude "Done ..."
 
 exit 0
 
-## Finished, what's written below is only a project ...
+## Finished, what's written below is only a project ...#{{{
 # ================================================
 # == I aimed to make a package for initrd   ======
 # == i will perhaps, do it later :-)        ======
@@ -509,4 +593,4 @@ if [ "$INITRD" = "yes" ]; then
     || shellout "makepkg failed for $PKGINITRD" 
 
 fi
-
+##}}}
diff --git a/paissad-git.SlackBuild b/paissad-git.SlackBuild
--- a/paissad-git.SlackBuild
+++ b/paissad-git.SlackBuild
@@ -26,12 +26,12 @@
 time_start_script=$(date +%s)
 
 PACKAGER_ID=${PACKAGER_ID:-$USER}
-PACKAGER=${PACKAGER:-$USER@$(cat /etc/HOSTNAME)}
+PACKAGER=${PACKAGER:-$USER@$(hostname -f)}
 DATE=$(LC_ALL=C date +%d-%b-%Y)
 
 PRGNAM=${PRGNAM:-}
 SRCNAM=${SRCNAM:-$PRGNAM}
-VERSION=${VERSION:-}
+VERSION=${VERSION:-}  # The version will be retreived automatically from the git repository
 ARCH=${ARCH:-$(uname -m)}
 BUILD=${BUILD:-1}
 CWD=${CWD:-`pwd`}
@@ -39,15 +39,14 @@ TMP=${TMP:-/tmp/SBp}
 PKG=${PKG:-$TMP/package-$PRGNAM}
 OUTPUT=${OUTPUT:-/tmp}
 EXT=${EXT:-tar.bz2}
-SOURCE=${SRCNAM}-${VERSION}.$EXT
-URL=${URL:-http://downloads.sourceforge.net/project/$SOURCE}
+GIT_URL=${GIT_URL:-}
 TAG=${TAG:-_paissad}
 PKGTYPE=${PKGTYPE:-tgz}
 PREFIX=${PREFIX:-"/usr"}
 NUMJOBS=${NUMJOBS:-}
-DOCS=${DOCS:-"CREDITS WHISHLIST ABOUT-NLS AUTHORS COPYING LICENSE* \
-CHANGES CHANGELOG* ChangeLog* HACKING INSTALL* MAINTAINERS NEWS \
-ReadMe* README* THANKS TODO Todo RELEASE* UPGRADING* FAQ Faq HELP* BUGS*"}
+DOCS=${DOCS:-"CREDITS WHISHLIST ABOUT-NLS AUTHORS COPYING LICENSE LICENSE.txt LICENSE.TXT \
+CHANGELOG ChangeLog CHANGELOG.txt CHANGELOG.TXT HACKING INSTALL INSTALL.txt \
+INSTALL.TXT MAINTAINERS NEWS ReadMe README README.txt THANKS TODO RELEASE UPGRADING FAQ HELP"}
 
 set -e
 
@@ -84,20 +83,50 @@ shellout(){
 warnout(){
     echo -e "${txtylw}Warning:${txtrst} $1"; sleep 3;
 }
-
+ # Determine the tarball extension:
+ case "$EXT" in
+     "tar.xz") TARCOMP="J" ;;
+     "tar.gz") TARCOMP="z" ;;
+     "tgz") TARCOMP="z" ;;
+     "tar.bz2") TARCOMP="j" ;;
+     *) echo "Archive can only have extension 'tar.xz', '.tar.gz' '.tar.bz2' or '.tgz'" ; 
+     exit 1 ;;
+ esac
+  
 # Download of the source !
-if [ ! -r $SOURCE ]; then
-    introduce "Start downloading $SOURCE" 
-    wget "$URL" || shellout "Downloading $SOURCE"
-    conclude "Download of $SOURCE finished successfully !"
+if [ ! -r ${SRCNAM}-$VERSION.$EXT ]; then
+    introduce "Start downloading ${SRCNAM} from git repository" 
+    git clone $GIT_URL $PRGNAM \
+    || shellout "Downloading ${SRCNAM}"
+    conclude "Download of ${SRCNAM} finished successfully !"
+	
+	# Let's get a kind of version
+    cd $CWD/$PRGNAM
+    #VERSION=$(git describe | tr '-' '.' | sed 's/\(.*\)\..*/\1/')
+	LOCAL_VERSION=`git rev-list HEAD | wc -l | awk '{ print $1 }'`
+	if git status | grep -q "modified:" ; then
+		LOCAL_VERSION="${LOCAL_VERSION}M"
+	fi
+	# If you want to add the 7 first characters of the hash, just uncomment
+	# the line below, that will be appended to VERSION
+	#VERSION="$VERSION.$(git rev-list HEAD -n 1 | cut -c 1-7)"
+	VERSION+="r${LOCAL_VERSION}"
+   	echo "VERSION = $VERSION"; sleep 2
+    cd $CWD; rm -rf $PRGNAM-$VERSION; mv $PRGNAM $PRGNAM-$VERSION
+
+	introduce "Compressing source ..."
+    tar --exclude .git -${TARCOMP}cvf $PRGNAM-$VERSION.$EXT $PRGNAM-$VERSION \
+    || shellout "Compressing source failed."
+    conclude "Compressing source finished successfully."
+    conclude "The file is $SRCNAM-$VERSION.$EXT" 
 fi
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP || exit 1
 rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$SOURCE \
-|| shellout "Extracting $SOURCE"
+tar xvf $CWD/${SRCNAM}-${VERSION}.$EXT \
+|| shellout "Extracting ${SRCNAM}-${VERSION}.$EXT"
 
 introduce "Start SlackBuild $PRGNAM-$VERSION"
 test -d $PRGNAM-$VERSION || \
@@ -115,14 +144,17 @@ chmod -R u+w,go+r-w,a-s .
 #-perm 400 \) -exec chmod 644 {} \;
 
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-D_GNU_SOURCE -O2 -march=i486 -mtune=i686"
+  SLACKCFLAGS="-O2 -march=i486 -mtune=i686"
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-D_GNU_SOURCE -O2 -march=i686 -mtune=i686"
+  SLACKCFLAGS="-O2 -march=i686 -mtune=i686"
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-D_GNU_SOURCE -O2 -fPIC"
+  SLACKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
   NUMJOBS=2
 fi
+
+#introduce "Running bootstrap"
+#./bootstrap || shellout "bootstrap failed."
 
 introduce "Running configure"
 CFLAGS="$SLKCFLAGS" \
@@ -143,7 +175,6 @@ make -j${NUMJOBS} || shellout "make failed."
 introduce "Running make install"
 make DESTDIR=$PKG install || shellout "make install failed"
 
-# strip binaries
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
 | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
@@ -167,11 +198,11 @@ $PRGNAM:
 $PRGNAM:
 $PRGNAM:
 $PRGNAM:
+$PRGNAM:
 $PRGNAM: 
-$PRGNAM: Homepage: 
+$PRGNAM: Homepage:
 $PRGNAM: 
 $PRGNAM: Packager: _PACKAGER on _BUILD_DATE
-$PRGNAM:
 EODESC
 
 # Install a doinst.sh, if it exists
